[build]
  command = "pnpm run build"
  functions = "functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  OTEL_EXPORTER_OTLP_ENDPOINT = "https://159336336075.collect.observeinc.com/v2/otel"
  OTEL_EXPORTER_OTLP_BEARER_TOKEN = "ds15mfSgBlKQVdG2edNV:SPQMc-N7hnIg2EwperqseHNsRKyMDumx"
  OTEL_SERVICE_NAME = "netlify-ts-functions"
  OTEL_SERVICE_VERSION = "1.0.0"
  OTEL_DEPLOYMENT_ENVIRONMENT = "production"

[dev]
  command = "pnpm run dev"
  
[dev.environment]
  NODE_ENV = "development"
  OTEL_EXPORTER_OTLP_ENDPOINT = "http://localhost:4318"
  OTEL_SERVICE_NAME = "netlify-ts-functions"
  OTEL_SERVICE_VERSION = "1.0.0"
  OTEL_DEPLOYMENT_ENVIRONMENT = "development"

[functions]
  directory = "functions"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/hello/"
  to = "/.netlify/functions/hello"
  status = 200