[build]
  command = "pnpm run build"
  functions = "functions"
  publish = "public"

[build.environment]
  OTEL_EXPORTER_OTLP_ENDPOINT = "http://localhost:4318"
  OTEL_SERVICE_NAME = "netlify-ts-functions"
  OTEL_SERVICE_VERSION = "1.0.0"
  NODE_ENV = "development"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200