[build]
  command = "pnpm run build"
  functions = "functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  OTEL_EXPORTER_OTLP_ENDPOINT = "https://collect.observeinc.com"
  OTEL_SERVICE_NAME = "netlify-ts-functions"
  OTEL_SERVICE_VERSION = "1.0.0"
  # The OBSERVE_INGEST_TOKEN should be set in Netlify's environment variables UI
  # OBSERVE_INGEST_TOKEN = "your_token_here"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200